title: WINDOWS10DO
description: Hub for my web projects and dashboards.
remote_theme: pages-themes/tactile

github_username: windows10do

header_pages:
  - index.md
  - about.md
  - contact.md

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - 404.md
